apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: default
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJraW5kcmVnaXN0cnkuYXp1cmVjci5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogImtpbmRyZWdpc3RyeSIsCiAgICAgICJwYXNzd29yZCI6ICJjOG9mMkhHUWp4OHBUVlBMdFoybUt5MmVVNG5tNGxZaXZ1RUZtVzJnbSsrQUNSQk1oMXI3IiwKICAgICAgImF1dGgiOiAiYTJsdVpISmxaMmx6ZEhKNU9tTTRiMll5U0VkUmFuZzRjRlJXVUV4MFdqSnRTM2t5WlZVMGJtMDBiRmxwZG5WRlJtMVhNbWR0S3l0QlExSkNUV2d4Y2pjPSIKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson

