kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30008  # NodePort in Kubernetes
        hostPort: 30008       # Port on the Azure VM
        protocol: TCP
  - role: worker
  - role: worker

